apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- headless-svc.yaml
- health-configmap.yaml
- scripts-configmap.yaml
- secret.yaml
- serviceaccount.yaml
- replicas/service.yaml
- replicas/statefulset.yaml
- master/service.yaml
- master/statefulset.yaml