---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis1
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.1.1
    app.kubernetes.io/instance: redis1
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "cnZackU4b1FEUg=="
